### ISSUE TITLE
Remove `print` and other logging statements

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#12]
## Feature description

The module module should not use `print` or other logging statements, such as in:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/a4b10d4d591ae32989587836a3d002659a71c024/Sources/CertLogic/CertLogic.swift#L69

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/a4b10d4d591ae32989587836a3d002659a71c024/Sources/CertLogic/CertLogic.swift#L71

## Problem and motivation

In the Corona-Warn-App, we have the data privacy requirement that nothing shall be logged by default. Thus, the current implementation that's using `print` statements is a blocker for adopting this module.

## Is this something you're interested in working on

we can file a PR if requested

**Comment by alexchornyi** [comment]
fixed in #15

**Comment by mlenkeit** [comment]
Thanks @alexchornyi!

Closing this, as #15 has been merged.
