### ISSUE TITLE
enum Result is conflicting with Swift.Result type

### ISSUE THREAD

**Issue by ArturFriesen** [eu-digital-green-certificates/dgc-certlogic-ios#19]
## Describe the bug

Using the data model conflicts with Swift.Result type and leads to a compiler error.
It can be resolved by explicitly using "Swift.Result".
But it would be nice if the types would not conflict, especially not with such a central one.

## Expected behaviour

Using the data model does not conflict with Swift.Result type.

## Possible Fix

Rename enum Result to something different.

**Comment by alexchornyi** [comment]
@ArturFriesen in this version we don't support Swift.Result, because in our architecture implementation in returning object we can receive not one Error, it's may be array of Error's
