### ISSUE TITLE
[VH] Non-boolean CertLogic result not handled

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#21]
## Describe the bug

If the CertLogic expression returns a non-boolean value, there is no corresponding ValidationResult.

Specifically, the `else` case is not handled here:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/14bcdce4ed19e151a9a3df1ea253db9a6238eeb7/Sources/CertLogic/CertLogic.swift#L58-L64

## Expected behaviour

Non-boolean values are mapped to a ValidationResult in state `open`.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

handle `else` case

## Additional context

n/a

**Comment by alexchornyi** [comment]
@mlenkeit please take a look #31  and if it's all good please close the bug.

**Comment by mlenkeit** [comment]
Looks good, thanks for the fix 👍
