### ISSUE TITLE
[VH] Typo in rule logic parameter name (in ExternalParameters)

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#22]
## Describe the bug

The ExternalParameters class has the attribute `issueCountryCode` (without `r`) instead of `issuerCountryCode`

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/14bcdce4ed19e151a9a3df1ea253db9a6238eeb7/Sources/CertLogic/ExternalParameter.swift

## Expected behaviour

The typo is fixed to align the parameter with the specification

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

fix the typo

## Additional context

n/a

**Comment by alexchornyi** [comment]
@mlenkeit fixed in #30

**Comment by mlenkeit** [comment]
LGTM, thanks for the fix 👍
