### ISSUE TITLE
Parameter `kid` cannot be set in `init` of ExternalParameter

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#23]
## Describe the bug

Parameter `kid` cannot be set from `init`

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/14bcdce4ed19e151a9a3df1ea253db9a6238eeb7/Sources/CertLogic/ExternalParameter.swift#L28-L44

## Expected behaviour

Parameter `kid` can be set from `init`

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

set `kid` in `init

## Additional context

n/a

**Comment by alexchornyi** [comment]
@mlenkeit fixed in #30 please take a look

**Comment by mlenkeit** [comment]
Thanks for the fix 👍
