### ISSUE TITLE
[VH] Rule filtering for `region` considers rules of all regions of a country if no region is provided

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#24]
## Describe the bug

The following code block tries to filter all general acceptance rules for the country and - if a `region` is set - continues to filter them for the provided region:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/14bcdce4ed19e151a9a3df1ea253db9a6238eeb7/Sources/CertLogic/CertLogic.swift#L114-L121

However, there's a flaw in this logic:

If no region is provided, the first sequence will contain rules of all the regions of the country.

## Expected behaviour

If no region is provided, only rules without an empty/nulled region should be filtered for. Otherwise, there can easily be contradicting rules from different regions.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

adjust filtering by region

## Additional context

- same applies to the other rule filtering logic pieces for invalidation rules and certificate type-specific rules

**Comment by mlenkeit** [comment]
Looks like this might be covered by #20

**Comment by alexchornyi** [comment]
@mlenkeit Yes, it's fixed. please confirm and close issue.

**Comment by mlenkeit** [comment]
LGTM, thanks for the fix 👍
