### ISSUE TITLE
[VH] Rule filtering by `version` incorrectly returns only a single rule

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#25]
## Describe the bug

The following code block tries to filter rules by version:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/14bcdce4ed19e151a9a3df1ea253db9a6238eeb7/Sources/CertLogic/CertLogic.swift#L133-L139

However, this statement effectively picks the _one_ rule out of the `generalRulesWithAcceptence` sequence with the maximum version.

No matter how many rules are passed to this check, only one rule is ever returned.

## Expected behaviour

Rules are grouped by their `Identifier`. If there are multiple rules with the same `Identifier` (that are valid considering the `validationClock`), the one with the maximum `Version` is selected.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

group by `identifier`, for each group, select the rule with the maximum `Version`

## Additional context

- same applies to the other rule filtering logic pieces for invalidation rules and certificate type-specific rules

**Comment by alexchornyi** [comment]
@mlenkeit fixed in #30

**Comment by mlenkeit** [comment]
LGTM, thanks for the fix 👍
