### ISSUE TITLE
Check for `Engine` attribute missing

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#26]
## Describe the bug

There is currently no check for the value of the `Engine` attribute of a rule:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/14bcdce4ed19e151a9a3df1ea253db9a6238eeb7/Sources/CertLogic/CertLogic.swift#L51-L70

## Expected behaviour

If a rule has the attribute `Engine` with a value other than `CERTLOGIC`, the rule is not evaluated but reported as `open`.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

add `if` statement

## Additional context

n/a

**Comment by SchulzeStTSI** [comment]
@mlenkeit @alexchornyi  please check #33

**Comment by alexchornyi** [comment]
@SchulzeStTSI I approved your PR please merge
@mlenkeit please review and close If all ok

**Comment by mlenkeit** [comment]
We're still waiting for the PR to be merged...
