### ISSUE TITLE
Check for `EngineVersion` attribute missing

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#27]
## Describe the bug

There is currently no check for the value of the `EngineVersion` attribute of a rule:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/14bcdce4ed19e151a9a3df1ea253db9a6238eeb7/Sources/CertLogic/CertLogic.swift#L51-L70

## Expected behaviour

If a rule has the attribute `Engine` with value `CERTLOGIC` and `EngineVersion` has a value other than `1.0.0`, the rule is  not evaluated but reported as `open`.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

add `if` statement

## Additional context

n/a

**Comment by SchulzeStTSI** [comment]
@mlenkeit @alexchornyi  please check #33

**Comment by alexchornyi** [comment]
@SchulzeStTSI I approved your PR please merge and close

**Comment by alexchornyi** [comment]
@mlenkeit please see latest changes and if all complete please close ticket

**Comment by mlenkeit** [comment]
We're still waiting for the PR to be merged...
