### ISSUE TITLE
Small typo "vaccination" in CertificationType

### ISSUE THREAD

**Issue by pascal-brause** [eu-digital-green-certificates/dgc-certlogic-ios#29]
## Describe the bug

The `CertificateType.vacctination` has a small typo.

## Expected behaviour

It should be named `CertificateType.vaccination`.

## Steps to reproduce the issue

Sources/CertLogic/CertLogic.swift: Line 233 and 250
Sources/CertLogic/Rule.swift: Line 20

## Possible Fix

Use renaming functionality of Xcode.

**Comment by alexchornyi** [comment]
@pascal-brause fixed in #30

**Comment by alexchornyi** [comment]
@pascal-brause please take a look, if it's all ok please close the bug.

**Comment by pascal-brause** [comment]
Seems correct. Thanks!
