### ISSUE TITLE
No support for Test Certificates and Recovery Certificates / Hard-coded to Vaccination Certificates

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#3]
## Describe the bug

The current code is hard-wired to Vaccination Certificates, e.g. in

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/a478f350183b467929450966d5a2cf7599bdff4d/Sources/CertLogic/CertLogic.swift#L40

Rules for other certificate types cannot be executed.

Also, there is no filtering of the `CertificateType` property, like there is in the Android library:

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/d9bd5136036f0db3c2648d70916cbaeb0851b2a3/engine/src/main/java/dgca/verifier/app/engine/data/source/RulesDataSource.kt#L27

## Expected behaviour

- `validate` does not do any filtering directly but receives a pre-filtered set of rules like it is on Android
- add utilities that facilitate filtering outside of the `validate` method (like there are on Android, see https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/d9bd5136036f0db3c2648d70916cbaeb0851b2a3/engine/src/main/java/dgca/verifier/app/engine/data/source/RulesDataSource.kt#L27)

## Steps to reproduce the issue

take a look at the code

## Technical details

n/a

## Possible Fix

see expected behavior

## Additional context

n/a

**Comment by mlenkeit** [comment]
seems to be fixed by https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/commit/9e09383896854d6c6f450d7fb8bdb1ec2cab0a43

**Comment by alexchornyi** [comment]
Yes, please see the latest commits. If all good we can close.

**Comment by mlenkeit** [comment]
Fixed with https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/commit/9e09383896854d6c6f450d7fb8bdb1ec2cab0a43, closing the issue 👍
