### ISSUE TITLE
Seperate Filterparameters from External Parameters

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-certlogic-ios#32]
Currently the External Parameters contain filterparameters like countryCode , Region, Certtype etc. Please seperate the Filterparameters in a seperate class "Filterparameter" which are added to the validate method. The external parameters should contain just fields which are passed to the JSON for logic execution.

**Comment by alexchornyi** [comment]
@SchulzeStTSI done please take a look the #34 if all good please approve and merge in to main branch

**Comment by alexchornyi** [comment]
@SchulzeStTSI and close the ticket. Thnx
