### ISSUE TITLE
[VH] Rule filtering by date ignores time zone information if milliseconds are absent

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#37]
## Describe the bug

A `ValidFrom` date `2021-07-22T16:34:33+02:00` is parsed as 16:34:33 UTC. Supposedly only happens if the date string does not have milliseconds.

## Expected behaviour

A `ValidFrom` date `2021-07-22T16:34:33+02:00` should parsed as 14:34:33 UTC

## Steps to reproduce the issue

Parse date `2021-07-22T16:34:33+02:00` and check output

## Technical details

n/a

## Possible Fix

somewhere here https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/257fa209c053ca4bc05629ece867f2f30bc45a3f/Sources/CertLogic/Date+.swift

## Additional context

n/a

**Comment by mlenkeit** [comment]
Generally, it might make sense to use the built-in ISO8106 parser as the first one instead of the last one:
https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/8b7f86a2aed4f2c60dd2c7c4f28eb129d9fe379d/Sources/CertLogic/Rule.swift#L58-L79

**Comment by nickguendling** [comment]
Just changing the order would not solve this issue as the `Date. Date.iso8601Formatter` does not have the `.withTimeZone` format option set and currently just ignores the time zone.

**Comment by alexchornyi** [comment]
@nickguendling fixed in #40
