### ISSUE TITLE
Engine attribute missing in Rule object

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#4]
## Describe the bug

The Rule object does not have an `Engine` attribute like it has on Android and as it is described in the official specification:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/a478f350183b467929450966d5a2cf7599bdff4d/Sources/CertLogic/Rule.swift#L24

## Expected behaviour

The Rule object deserializes the `Engine` attribute

## Steps to reproduce the issue

take a look at the code

## Technical details

n/a

## Possible Fix

see expected behavior

## Additional context

n/a

**Comment by mlenkeit** [comment]
Looks like this was added with https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/commit/8961b39ee6b07139e15ed345d69892f04a55c420

**Comment by alexchornyi** [comment]
fixed by https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/commit/8961b39ee6b07139e15ed345d69892f04a55c420
