### ISSUE TITLE
Allowed Syntax differs from Specification

### ISSUE THREAD

**Issue by ubamrein** [eu-digital-green-certificates/dgc-certlogic-ios#42]
## Describe the bug

See discussion here: https://github.com/ehn-dcc-development/dgc-business-rules/issues/67

In order to avoid different behaviour on Android/iOS I would suggest aligning one or the other library (or as it seems the iOS implementation here). 

I'm not sure, how this is best achieved. The obvious chose would be to just fix the two issues with `var` and `!`.

**Comment by kerstin-oppermann-tsi** [comment]
@ubamrein do you think this issue should be still open? Or can I close it? The related discussion is closed.
