### ISSUE TITLE
Dependency of 'json-logic-swift' is not updated to 1.1.7

### ISSUE THREAD

**Issue by ArturFriesen** [eu-digital-green-certificates/dgc-certlogic-ios#43]
## Describe the bug

The documentation was updated to support 'extractFromUVCI' but the dependency to 'json-logic-swift' was not updated.
The version 1.1.7 of  'json-logic-swift' contains support for 'extractFromUVCI'.

## Expected behaviour

Dependency of 'json-logic-swift' is updated to 1.1.7

**Comment by SchulzeStTSI** [comment]
@ArturFriesen we update to 1.1.8 directly

**Comment by alexchornyi** [comment]
@ArturFriesen jsonLogic version 1.1.7 was created 22 days ago and available for all users. All you need to do - it's only update swift package in your project if it's not updated automatically
https://github.com/eu-digital-green-certificates/json-logic-swift/releases/tag/1.1.7

**Comment by ArturFriesen** [comment]
@alexchornyi We are not using json-logic-swift directly. We are using this package. And this package, inside, was pointing to a older version of json-logic-swift.

@SchulzeStTSI Thanks for updating directly to 1.1.8! Please let me know if its done, so I can replace our fork with your repo.

**Comment by SchulzeStTSI** [comment]
@ArturFriesen done. @alexchornyi  Thank you:)
