### ISSUE TITLE
Schema version checked instead of rule engine version when determining open rules

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#6]
## Describe the bug

The `SchemaVersion` attribute of a rule is checked against the `ver` attribute of the DCC to determine if the rule is `open` or not (instead of `pass` or `fail`)

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/a478f350183b467929450966d5a2cf7599bdff4d/Sources/CertLogic/CertLogic.swift#L55-L57

## Expected behaviour

As per the specification, a rule can only be `open` if `EngineVersion` is not compatible:

> 5.4.1 Incompatible Rule Engine Versions
In the case of an incompatible engine version (rule engine version> current version), the technical validation has to be performed a human readable fallback. 

## Steps to reproduce the issue

look at the code

## Technical details

n/a

## Possible Fix

check for engine version instead of schema version

## Additional context

n/a

**Comment by alexchornyi** [comment]
@mlenkeit  open status will be added to Android with latest commits and it's status only for rule with scheme version miss match with specific error for the user. All this added in latest commits. 
Please see, if it's good we can close this issue.
