### ISSUE TITLE
Integrate Hashcheckup 

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-certlogic-ios#7]
After downloading a business rule/valueset, the hash of the received content must be checked against the hash of the trustlist, to ensure that the file which was downloaded is the correct one. This can be resolved over integrating an interceptor to the http client. If the hash is not correct, the rule should not be updated (if exists) or should be ignored during the download(please show a hint anywhere that there is an problem)

**Comment by alexchornyi** [comment]
@SchulzeStTSI it's completed for wallet app and verifier app. Please close
